import os
import pandas as pd
import re

class VaspParser:
    """Parses VASP output files: CONTCAR/POSCAR, POTCAR, and ACF.dat"""
    
    @staticmethod
    def parse_structure(filepath):
        """
        Parses CONTCAR or POSCAR using pymatgen.
        Returns a tuple of (Structure object, list of element symbols for each atom).
        """
        from pymatgen.core.structure import Structure  # lazy: pymatgen is heavy (~17s)
        
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"Structure file not found: {filepath}")
        
        struct = Structure.from_file(filepath)
        elements = [site.specie.symbol for site in struct]
        
        return struct, elements

    @staticmethod
    def parse_potcar_zval(filepath):
        """
        Parses POTCAR to extract ZVAL for each pseudo-potential.
        Returns a list of ZVAL values corresponding to each element type in the POTCAR order.
        """
        from pymatgen.io.vasp import Potcar  # lazy: pymatgen.io.vasp is heavy (~5s)
        
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"POTCAR not found: {filepath}")
        
        potcar = Potcar.from_file(filepath)
        zvals = [p.zval for p in potcar]
        symbols = [p.element for p in potcar]
        
        # Return a dictionary mapping the ordered element symbol to its ZVAL.
        # Note: If multiple pseudo-potentials for the same element exist (e.g. Fe, Fe_pv), 
        # this simple dict mapping might overwrite. For advanced targeting, the calculator will handle it.
        # Here we return a list to keep order, and a basic dict.
        
        zval_dict = {}
        for sym, zval in zip(symbols, zvals):
            zval_dict[sym] = zval
            
        return zval_dict, zvals, symbols

    @staticmethod
    def parse_acf(filepath):
        """
        Parses the ACF.dat file generated by the bader executable.
        Returns a pandas DataFrame containing the atomic coordinates, charge, min distance, and volume.
        """
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"ACF.dat not found: {filepath}")
            
        data = []
        with open(filepath, 'r') as f:
            lines = f.readlines()
            
        # ACF.dat format usually starts with 2 header lines, then data, then 4 footer lines
        # Header:
        #    #         X           Y           Z       CHARGE      MIN DIST   ATOMIC VOL
        # --------------------------------------------------------------------------------
        
        start_parsing = False
        for line in lines:
            line = line.strip()
            if line.startswith("---"):
                start_parsing = not start_parsing # Toggle parsing flag
                continue
            
            if start_parsing:
                parts = line.split()
                if len(parts) >= 7:
                    try:
                        atom_idx = int(parts[0])
                        x = float(parts[1])
                        y = float(parts[2])
                        z = float(parts[3])
                        charge = float(parts[4])
                        min_dist = float(parts[5])
                        vol = float(parts[6])
                        
                        data.append({
                            "Atom": atom_idx,
                            "X": x,
                            "Y": y,
                            "Z": z,
                            "CHARGE": charge,
                            "Min_Dist": min_dist,
                            "Volume": vol
                        })
                    except ValueError:
                        pass # Skip malformed lines

        df = pd.DataFrame(data)
        return df

    @staticmethod
    def parse_chgcar_density(filepath):
        """
        Optional utility if we ever need to read raw CHGCAR directly (not usually needed for bader running).
        """
        pass
